CREATE TABLE ACCOUNT
( 
  EMLOYEE_ID INT not null PRIMARY KEY, 
  PASSWORD TEXT,
  isACTIVE BIT,
  ROLE INT
);
CREATE TABLE POSITION
(
POSITION_ID INT NOT NULL PRIMARY KEY,
POSITION_NAME VARCHAR(50),
SPECIALTY VARCHAR(50),
);
CREATE TABLE EMPLOYEE
(
EMLOYEE_ID INT NOT NULL PRIMARY KEY,
NAM VARCHAR(50),
IDENTITY_NUMBER VARCHAR(15),
PHONE VARCHAR(15),
GENDER BIT,
DATE_OF_BIRTH DATE,
ADDRESS NVARCHAR(100),
POSITION INT,
DATE_START_WORK DATE,
SALARY INT
);
ALTER TABLE ACCOUNT ADD FOREIGN KEY (EMLOYEE_ID) REFERENCES POSITION(POSITION_ID);